"""Static realistic snapshot data for the mock OmniFocus simulator.

The ``SIMULATOR_SNAPSHOT`` dictionary mirrors the structure produced by
the OmniFocus bridge script -- camelCase keys, RFC 3339 datetime strings,
and representative data covering the main entity types a power user
would have.
"""

from __future__ import annotations

SIMULATOR_SNAPSHOT: dict[str, object] = {
    "tasks": [
        {
            "id": "task-sim-001",
            "name": "Review Q1 budget proposal",
            "note": "Check numbers against last quarter actuals",
            "completed": False,
            "completedByChildren": False,
            "flagged": True,
            "effectiveFlagged": True,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": False,
            "dueDate": "2026-03-15T09:00:00+00:00",
            "tags": ["tag-sim-001"],
        },
        {
            "id": "task-sim-002",
            "name": "Buy groceries",
            "note": "",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": False,
            "dueDate": None,
            "tags": ["tag-sim-003"],
        },
        {
            "id": "task-sim-003",
            "name": "Draft project charter",
            "note": "Include scope, timeline, and stakeholder list",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": False,
            "dueDate": "2026-03-20T17:00:00+00:00",
            "tags": ["tag-sim-001"],
        },
        {
            "id": "task-sim-004",
            "name": "Call dentist for appointment",
            "note": "",
            "completed": True,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": False,
            "effectiveActive": False,
            "status": "Completed",
            "inInbox": False,
            "dueDate": None,
            "tags": ["tag-sim-002"],
        },
        {
            "id": "task-sim-005",
            "name": "Process inbox",
            "note": "",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": True,
            "dueDate": None,
            "tags": [],
        },
        {
            "id": "task-sim-006",
            "name": "Prepare slide deck for Monday standup",
            "note": "Focus on sprint velocity and blockers",
            "completed": False,
            "completedByChildren": False,
            "flagged": True,
            "effectiveFlagged": True,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": False,
            "dueDate": "2026-03-09T08:00:00+00:00",
            "tags": ["tag-sim-001"],
        },
        {
            "id": "task-sim-007",
            "name": "Read chapter 5 of Design Patterns",
            "note": "",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": False,
            "dueDate": None,
            "tags": ["tag-sim-002"],
        },
        {
            "id": "task-sim-008",
            "name": "Follow up with vendor on pricing",
            "note": "Waiting for reply since March 1",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": False,
            "dueDate": "2026-03-10T12:00:00+00:00",
            "tags": ["tag-sim-004"],
        },
        {
            "id": "task-sim-009",
            "name": "Set up CI pipeline for new repo",
            "note": "GitHub Actions with uv cache",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": True,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": False,
            "dueDate": None,
            "tags": ["tag-sim-001"],
        },
        {
            "id": "task-sim-010",
            "name": "Schedule vet checkup for Luna",
            "note": "",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": False,
            "shouldUseFloatingTimeZone": False,
            "active": True,
            "effectiveActive": True,
            "status": "Available",
            "inInbox": True,
            "dueDate": None,
            "tags": [],
        },
    ],
    "projects": [
        {
            "id": "proj-sim-001",
            "name": "Q1 Planning",
            "note": "Quarterly planning cycle",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": True,
            "shouldUseFloatingTimeZone": False,
            "taskStatus": "Available",
            "containsSingletonActions": False,
            "status": "Active",
        },
        {
            "id": "proj-sim-002",
            "name": "Home Renovation",
            "note": "Kitchen and bathroom remodel",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": True,
            "hasChildren": True,
            "shouldUseFloatingTimeZone": False,
            "taskStatus": "Available",
            "containsSingletonActions": False,
            "status": "Active",
        },
        {
            "id": "proj-sim-003",
            "name": "Open Source Contributions",
            "note": "",
            "completed": False,
            "completedByChildren": False,
            "flagged": False,
            "effectiveFlagged": False,
            "sequential": False,
            "hasChildren": True,
            "shouldUseFloatingTimeZone": False,
            "taskStatus": "Available",
            "containsSingletonActions": True,
            "status": "Active",
        },
    ],
    "tags": [
        {
            "id": "tag-sim-001",
            "name": "work",
            "active": True,
            "effectiveActive": True,
            "status": "Active",
            "allowsNextAction": True,
        },
        {
            "id": "tag-sim-002",
            "name": "personal",
            "active": True,
            "effectiveActive": True,
            "status": "Active",
            "allowsNextAction": True,
        },
        {
            "id": "tag-sim-003",
            "name": "errands",
            "active": True,
            "effectiveActive": True,
            "status": "Active",
            "allowsNextAction": True,
        },
        {
            "id": "tag-sim-004",
            "name": "waiting-for",
            "active": True,
            "effectiveActive": True,
            "status": "Active",
            "allowsNextAction": False,
        },
    ],
    "folders": [
        {
            "id": "folder-sim-001",
            "name": "Work",
            "active": True,
            "effectiveActive": True,
            "status": "Active",
        },
        {
            "id": "folder-sim-002",
            "name": "Personal",
            "active": True,
            "effectiveActive": True,
            "status": "Active",
        },
    ],
    "perspectives": [
        {
            "id": None,
            "name": "Inbox",
            "builtin": True,
        },
        {
            "id": None,
            "name": "Forecast",
            "builtin": True,
        },
        {
            "id": "persp-sim-001",
            "name": "Due This Week",
            "builtin": False,
        },
    ],
}
