"""Static realistic snapshot data for the mock OmniFocus simulator.

The ``SIMULATOR_SNAPSHOT`` dictionary mirrors the new model shape --
camelCase keys, RFC 3339 datetime strings, two-axis status model
(urgency + availability), and snake_case enum values.

All entities include the full field set required by the updated models:
- url, added, modified on all entity types
- Tags as TagRef objects {id, name}
- Two-axis status (urgency, availability) on tasks and projects
- Per-entity status enums (TagStatus, FolderStatus) with snake_case values
- Perspective without builtin (computed in Python from id is None)
"""

from __future__ import annotations

SIMULATOR_SNAPSHOT: dict[str, object] = {
    "tasks": [
        {
            "id": "task-sim-001",
            "name": "Review Q1 budget proposal",
            "url": "omnifocus:///task/task-sim-001",
            "note": "Check numbers against last quarter actuals",
            "added": "2026-02-15T08:00:00+00:00",
            "modified": "2026-03-01T10:00:00+00:00",
            "urgency": "due_soon",
            "availability": "available",
            "flagged": True,
            "effectiveFlagged": True,
            "hasChildren": False,
            "inInbox": False,
            "dueDate": "2026-03-15T09:00:00+00:00",
            "deferDate": None,
            "effectiveDueDate": "2026-03-15T09:00:00+00:00",
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": 30,
            "repetitionRule": None,
            "project": "proj-sim-001",
            "parent": None,
            "tags": [{"id": "tag-sim-001", "name": "work"}],
        },
        {
            "id": "task-sim-002",
            "name": "Buy groceries",
            "url": "omnifocus:///task/task-sim-002",
            "note": "",
            "added": "2026-03-01T12:00:00+00:00",
            "modified": "2026-03-01T12:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": False,
            "inInbox": False,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "project": None,
            "parent": None,
            "tags": [{"id": "tag-sim-003", "name": "errands"}],
        },
        {
            "id": "task-sim-003",
            "name": "Draft project charter",
            "url": "omnifocus:///task/task-sim-003",
            "note": "Include scope, timeline, and stakeholder list",
            "added": "2026-02-20T14:00:00+00:00",
            "modified": "2026-03-02T09:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": False,
            "inInbox": False,
            "dueDate": "2026-03-20T17:00:00+00:00",
            "deferDate": None,
            "effectiveDueDate": "2026-03-20T17:00:00+00:00",
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": 60,
            "repetitionRule": None,
            "project": "proj-sim-001",
            "parent": None,
            "tags": [{"id": "tag-sim-001", "name": "work"}],
        },
        {
            "id": "task-sim-004",
            "name": "Call dentist for appointment",
            "url": "omnifocus:///task/task-sim-004",
            "note": "",
            "added": "2026-02-10T08:00:00+00:00",
            "modified": "2026-03-01T15:00:00+00:00",
            "urgency": "none",
            "availability": "completed",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": False,
            "inInbox": False,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": "2026-03-01T15:00:00+00:00",
            "effectiveCompletionDate": "2026-03-01T15:00:00+00:00",
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "project": None,
            "parent": None,
            "tags": [{"id": "tag-sim-002", "name": "personal"}],
        },
        {
            "id": "task-sim-005",
            "name": "Process inbox",
            "url": "omnifocus:///task/task-sim-005",
            "note": "",
            "added": "2026-03-05T07:00:00+00:00",
            "modified": "2026-03-05T07:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": False,
            "inInbox": True,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "project": None,
            "parent": None,
            "tags": [],
        },
        {
            "id": "task-sim-006",
            "name": "Prepare slide deck for Monday standup",
            "url": "omnifocus:///task/task-sim-006",
            "note": "Focus on sprint velocity and blockers",
            "added": "2026-03-04T10:00:00+00:00",
            "modified": "2026-03-05T08:00:00+00:00",
            "urgency": "due_soon",
            "availability": "available",
            "flagged": True,
            "effectiveFlagged": True,
            "hasChildren": False,
            "inInbox": False,
            "dueDate": "2026-03-09T08:00:00+00:00",
            "deferDate": None,
            "effectiveDueDate": "2026-03-09T08:00:00+00:00",
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": 45,
            "repetitionRule": None,
            "project": "proj-sim-001",
            "parent": None,
            "tags": [{"id": "tag-sim-001", "name": "work"}],
        },
        {
            "id": "task-sim-007",
            "name": "Read chapter 5 of Design Patterns",
            "url": "omnifocus:///task/task-sim-007",
            "note": "",
            "added": "2026-02-25T18:00:00+00:00",
            "modified": "2026-02-25T18:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": False,
            "inInbox": False,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "project": None,
            "parent": None,
            "tags": [{"id": "tag-sim-002", "name": "personal"}],
        },
        {
            "id": "task-sim-008",
            "name": "Follow up with vendor on pricing",
            "url": "omnifocus:///task/task-sim-008",
            "note": "Waiting for reply since March 1",
            "added": "2026-03-01T09:00:00+00:00",
            "modified": "2026-03-03T11:00:00+00:00",
            "urgency": "due_soon",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": False,
            "inInbox": False,
            "dueDate": "2026-03-10T12:00:00+00:00",
            "deferDate": None,
            "effectiveDueDate": "2026-03-10T12:00:00+00:00",
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "project": "proj-sim-001",
            "parent": None,
            "tags": [{"id": "tag-sim-004", "name": "waiting-for"}],
        },
        {
            "id": "task-sim-009",
            "name": "Set up CI pipeline for new repo",
            "url": "omnifocus:///task/task-sim-009",
            "note": "GitHub Actions with uv cache",
            "added": "2026-03-02T14:00:00+00:00",
            "modified": "2026-03-04T16:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": True,
            "inInbox": False,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": 120,
            "repetitionRule": None,
            "project": "proj-sim-003",
            "parent": None,
            "tags": [{"id": "tag-sim-001", "name": "work"}],
        },
        {
            "id": "task-sim-010",
            "name": "Schedule vet checkup for Luna",
            "url": "omnifocus:///task/task-sim-010",
            "note": "",
            "added": "2026-03-05T09:00:00+00:00",
            "modified": "2026-03-05T09:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": False,
            "inInbox": True,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "project": None,
            "parent": None,
            "tags": [],
        },
    ],
    "projects": [
        {
            "id": "proj-sim-001",
            "name": "Q1 Planning",
            "url": "omnifocus:///project/proj-sim-001",
            "note": "Quarterly planning cycle",
            "added": "2026-01-10T08:00:00+00:00",
            "modified": "2026-03-01T10:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": True,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "lastReviewDate": "2026-03-01T08:00:00+00:00",
            "nextReviewDate": "2026-03-08T08:00:00+00:00",
            "reviewInterval": {"steps": 7, "unit": "days"},
            "nextTask": "task-sim-001",
            "folder": "folder-sim-001",
            "tags": [],
        },
        {
            "id": "proj-sim-002",
            "name": "Home Renovation",
            "url": "omnifocus:///project/proj-sim-002",
            "note": "Kitchen and bathroom remodel",
            "added": "2026-01-15T10:00:00+00:00",
            "modified": "2026-02-28T14:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": True,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "lastReviewDate": "2026-02-28T08:00:00+00:00",
            "nextReviewDate": "2026-03-14T08:00:00+00:00",
            "reviewInterval": {"steps": 14, "unit": "days"},
            "nextTask": None,
            "folder": "folder-sim-002",
            "tags": [],
        },
        {
            "id": "proj-sim-003",
            "name": "Open Source Contributions",
            "url": "omnifocus:///project/proj-sim-003",
            "note": "",
            "added": "2026-02-01T12:00:00+00:00",
            "modified": "2026-03-04T16:00:00+00:00",
            "urgency": "none",
            "availability": "available",
            "flagged": False,
            "effectiveFlagged": False,
            "hasChildren": True,
            "dueDate": None,
            "deferDate": None,
            "effectiveDueDate": None,
            "effectiveDeferDate": None,
            "completionDate": None,
            "effectiveCompletionDate": None,
            "plannedDate": None,
            "effectivePlannedDate": None,
            "dropDate": None,
            "effectiveDropDate": None,
            "estimatedMinutes": None,
            "repetitionRule": None,
            "lastReviewDate": "2026-03-04T08:00:00+00:00",
            "nextReviewDate": "2026-03-11T08:00:00+00:00",
            "reviewInterval": {"steps": 7, "unit": "days"},
            "nextTask": "task-sim-009",
            "folder": "folder-sim-001",
            "tags": [],
        },
    ],
    "tags": [
        {
            "id": "tag-sim-001",
            "name": "work",
            "url": "omnifocus:///tag/tag-sim-001",
            "added": "2026-01-01T08:00:00+00:00",
            "modified": "2026-01-01T08:00:00+00:00",
            "status": "active",
            "childrenAreMutuallyExclusive": False,
            "parent": None,
        },
        {
            "id": "tag-sim-002",
            "name": "personal",
            "url": "omnifocus:///tag/tag-sim-002",
            "added": "2026-01-01T08:00:00+00:00",
            "modified": "2026-01-01T08:00:00+00:00",
            "status": "active",
            "childrenAreMutuallyExclusive": False,
            "parent": None,
        },
        {
            "id": "tag-sim-003",
            "name": "errands",
            "url": "omnifocus:///tag/tag-sim-003",
            "added": "2026-01-01T08:00:00+00:00",
            "modified": "2026-01-01T08:00:00+00:00",
            "status": "active",
            "childrenAreMutuallyExclusive": False,
            "parent": None,
        },
        {
            "id": "tag-sim-004",
            "name": "waiting-for",
            "url": "omnifocus:///tag/tag-sim-004",
            "added": "2026-01-01T08:00:00+00:00",
            "modified": "2026-01-01T08:00:00+00:00",
            "status": "active",
            "childrenAreMutuallyExclusive": False,
            "parent": None,
        },
    ],
    "folders": [
        {
            "id": "folder-sim-001",
            "name": "Work",
            "url": "omnifocus:///folder/folder-sim-001",
            "added": "2026-01-01T08:00:00+00:00",
            "modified": "2026-01-01T08:00:00+00:00",
            "status": "active",
            "parent": None,
        },
        {
            "id": "folder-sim-002",
            "name": "Personal",
            "url": "omnifocus:///folder/folder-sim-002",
            "added": "2026-01-01T08:00:00+00:00",
            "modified": "2026-01-01T08:00:00+00:00",
            "status": "active",
            "parent": None,
        },
    ],
    "perspectives": [
        {
            "id": None,
            "name": "Inbox",
        },
        {
            "id": None,
            "name": "Forecast",
        },
        {
            "id": "persp-sim-001",
            "name": "Due This Week",
        },
    ],
}
