# ruff: noqa: E501 — inline comments on field sets are more readable without wrapping
"""Normalization and filtering helpers for golden master comparison.

Strips dynamic fields (generated by OmniFocus at runtime) so that golden
master fixtures captured from the real Bridge can be compared against
InMemoryBridge output deterministically.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Dynamic fields per entity type (D-15, D-18)
#
# - VOLATILE: different every run, never matchable — stripped entirely
# - PRESENCE_CHECK: timestamps that vary but presence matters — non-null → "<set>"
# - UNCOMPUTED: deterministic but InMemoryBridge doesn't compute yet — stripped
#
# Remove a field from UNCOMPUTED when InMemoryBridge learns the computation --
# the contract test will then start verifying it automatically.
# ---------------------------------------------------------------------------

# Fields that differ every run -- will never match between the real Bridge and InMemoryBridge
VOLATILE_TASK_FIELDS: set[str] = {
    "id",  # OmniFocus generates unique IDs; InMemoryBridge generates mem-{uuid}
    "url",  # derived from id (omnifocus:///task/{id})
    "added",  # timestamp set by OmniFocus at creation time
    "modified",  # timestamp updated by OmniFocus on every mutation
    # completionDate and dropDate moved to PRESENCE_CHECK_TASK_FIELDS (D-08)
}
VOLATILE_PROJECT_FIELDS: set[str] = {
    "id",  # OmniFocus generates unique IDs
    "url",  # derived from id
    "added",  # timestamp set at creation
    "modified",  # timestamp updated on mutation
}
VOLATILE_TAG_FIELDS: set[str] = {
    "id",  # OmniFocus generates unique IDs
    "url",  # derived from id
    "added",  # timestamp set at creation
    "modified",  # timestamp updated on mutation
}

# Fields that are deterministic but InMemoryBridge doesn't compute yet.
# Remove from here when InMemoryBridge learns the computation -- the contract
# test will then start verifying the field automatically.
UNCOMPUTED_TASK_FIELDS: set[str] = {
    # --- Status computation ---
    #
    # The status field is intentionally omitted to prevent unnecessary complexity.
    #
    # This is acceptable because:
    #  1. The normal read path uses HybridRepository → SQLite, which stores
    #     urgency/availability as separate columns.
    #  2. The bridge read path is for BridgeOnlyRepository, which is a fallback mode, and intentionally degraded => Prevents unnecessary complexity for a fallback mode (fully documented)
    #  3. Implementing the status computation would mean implementing the logic we intentionally scoped out (see 2.)
    "status",  # see above
}
UNCOMPUTED_PROJECT_FIELDS: set[str] = {
    "taskStatus",  # same reasoning as task status
    "completionDate",  # no "complete a project" operation in InMemoryBridge
    "effectiveCompletionDate",  # adapter strips this for projects (dead field), but present in raw bridge output
    "repetitionRule",  # InMemoryBridge doesn't simulate project repeat rules
    "nextTask",  # OmniFocus computes "next available task"; InMemoryBridge doesn't
}
UNCOMPUTED_TAG_FIELDS: set[str] = set()  # Tags are fully computed

# Fields where null-vs-non-null is deterministic but exact timestamp differs.
# Normalized to "<set>" sentinel (non-null) or None (null) for comparison.
PRESENCE_CHECK_TASK_FIELDS: set[str] = {
    "completionDate",  # InMemoryBridge sets this, but timestamp differs per run (D-08)
    "dropDate",  # InMemoryBridge sets this, but timestamp differs per run (D-08)
    "effectiveCompletionDate",  # Same presence-check pattern (D-09)
    "effectiveDropDate",  # Same presence-check pattern (D-09)
}

# Combined sets used by normalize_for_comparison
DYNAMIC_TASK_FIELDS = VOLATILE_TASK_FIELDS | UNCOMPUTED_TASK_FIELDS
DYNAMIC_PROJECT_FIELDS = VOLATILE_PROJECT_FIELDS | UNCOMPUTED_PROJECT_FIELDS
DYNAMIC_TAG_FIELDS = VOLATILE_TAG_FIELDS | UNCOMPUTED_TAG_FIELDS

_DYNAMIC_FIELDS_BY_TYPE: dict[str, set[str]] = {
    "task": DYNAMIC_TASK_FIELDS,
    "project": DYNAMIC_PROJECT_FIELDS,
    "tag": DYNAMIC_TAG_FIELDS,
}

_PRESENCE_CHECK_BY_TYPE: dict[str, set[str]] = {
    "task": PRESENCE_CHECK_TASK_FIELDS,
    "project": set(),
    "tag": set(),
}


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def normalize_for_comparison(entity: dict[str, Any], entity_type: str) -> dict[str, Any]:
    """Strip dynamic fields and apply presence-check normalization.

    Returns a new dict without volatile/uncomputed fields.  Presence-check
    fields are normalized to ``"<set>"`` (non-null) or ``None`` (null) so
    that timestamp differences between runs are ignored while still
    verifying that the field was populated (or not).
    """
    fields_to_strip = _DYNAMIC_FIELDS_BY_TYPE.get(entity_type, set())
    presence_fields = _PRESENCE_CHECK_BY_TYPE.get(entity_type, set())
    result: dict[str, Any] = {}
    for k, v in entity.items():
        if k in fields_to_strip:
            continue
        if k in presence_fields:
            result[k] = "<set>" if v is not None else None
        else:
            result[k] = v
    return result


def normalize_response(response: dict[str, Any]) -> dict[str, Any]:
    """Strip ``id`` from a write response dict for comparison.

    Write operations (add_task, edit_task) return ``{id, name}``.
    The ``id`` is dynamic; only ``name`` is stable.
    """
    return {k: v for k, v in response.items() if k != "id"}


def normalize_state(state: dict[str, Any]) -> dict[str, Any]:
    """Normalize an entire state snapshot for deterministic comparison.

    For each entity list (tasks, projects, tags), strips dynamic fields
    and sorts by ``name`` for stable ordering.
    """
    type_map = {"tasks": "task", "projects": "project", "tags": "tag"}
    result: dict[str, Any] = {}
    for key, entity_type in type_map.items():
        entities = state.get(key, [])
        normalized = [normalize_for_comparison(e, entity_type) for e in entities]
        result[key] = sorted(normalized, key=lambda e: e.get("name", ""))
    return result


def filter_to_known_ids(
    raw: dict[str, Any],
    known_task_ids: set[str],
    known_project_id_set: set[str],
    known_tag_ids: set[str],
) -> dict[str, Any]:
    """Filter a full get_all response to only entities with known IDs.

    Used to extract test-created entities from a full OmniFocus database
    snapshot, ensuring the golden master contains no private data (D-09/D-17).
    """
    return {
        "tasks": [t for t in raw.get("tasks", []) if t["id"] in known_task_ids],
        "projects": [p for p in raw.get("projects", []) if p["id"] in known_project_id_set],
        "tags": [g for g in raw.get("tags", []) if g["id"] in known_tag_ids],
    }
