"""Normalization and filtering helpers for golden master comparison.

Strips dynamic fields (generated by OmniFocus at runtime) so that golden
master fixtures captured from RealBridge can be compared against
InMemoryBridge output deterministically.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Dynamic fields per entity type (D-15, D-18)
# ---------------------------------------------------------------------------

DYNAMIC_TASK_FIELDS: set[str] = {
    "id",
    "url",
    "added",
    "modified",
    "completionDate",
    "dropDate",
    "effectiveDueDate",
    "effectiveDeferDate",
    "effectiveCompletionDate",
    "effectivePlannedDate",
    "effectiveDropDate",
    "repetitionRule",
}

DYNAMIC_PROJECT_FIELDS: set[str] = {
    "id",
    "url",
    "added",
    "modified",
    "completionDate",
    "repetitionRule",
    "nextTask",
}

DYNAMIC_TAG_FIELDS: set[str] = {
    "id",
    "url",
    "added",
    "modified",
}

_DYNAMIC_FIELDS_BY_TYPE: dict[str, set[str]] = {
    "task": DYNAMIC_TASK_FIELDS,
    "project": DYNAMIC_PROJECT_FIELDS,
    "tag": DYNAMIC_TAG_FIELDS,
}


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def normalize_for_comparison(entity: dict[str, Any], entity_type: str) -> dict[str, Any]:
    """Strip dynamic fields from an entity dict for deterministic comparison.

    Returns a new dict without the fields that vary between runs
    (timestamps, IDs, computed dates, repetition rules).
    """
    fields_to_strip = _DYNAMIC_FIELDS_BY_TYPE.get(entity_type, set())
    return {k: v for k, v in entity.items() if k not in fields_to_strip}


def normalize_response(response: dict[str, Any]) -> dict[str, Any]:
    """Strip ``id`` from a write response dict for comparison.

    Write operations (add_task, edit_task) return ``{id, name}``.
    The ``id`` is dynamic; only ``name`` is stable.
    """
    return {k: v for k, v in response.items() if k != "id"}


def normalize_state(state: dict[str, Any]) -> dict[str, Any]:
    """Normalize an entire state snapshot for deterministic comparison.

    For each entity list (tasks, projects, tags), strips dynamic fields
    and sorts by ``name`` for stable ordering.
    """
    type_map = {"tasks": "task", "projects": "project", "tags": "tag"}
    result: dict[str, Any] = {}
    for key, entity_type in type_map.items():
        entities = state.get(key, [])
        normalized = [normalize_for_comparison(e, entity_type) for e in entities]
        result[key] = sorted(normalized, key=lambda e: e.get("name", ""))
    return result


def filter_to_known_ids(
    raw: dict[str, Any],
    known_task_ids: set[str],
    known_project_ids: set[str],
    known_tag_ids: set[str],
) -> dict[str, Any]:
    """Filter a full get_all response to only entities with known IDs.

    Used to extract test-created entities from a full OmniFocus database
    snapshot, ensuring the golden master contains no private data (D-09/D-17).
    """
    return {
        "tasks": [t for t in raw.get("tasks", []) if t["id"] in known_task_ids],
        "projects": [p for p in raw.get("projects", []) if p["id"] in known_project_ids],
        "tags": [g for g in raw.get("tags", []) if g["id"] in known_tag_ids],
    }
